# Generated by Django 4.2.7 on 2023-11-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_zno_outid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zno',
            name='AREANAME',
            field=models.CharField(db_column='AREANAME', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='Birth',
            field=models.CharField(db_column='Birth', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='ClassLangName',
            field=models.CharField(db_column='ClassLangName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='ClassProfileNAME',
            field=models.CharField(db_column='ClassProfileNAME', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='EOAreaName',
            field=models.CharField(db_column='EOAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='EONAME',
            field=models.CharField(db_column='EONAME', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='EOParent',
            field=models.CharField(db_column='EOParent', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='EORegName',
            field=models.CharField(db_column='EORegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='EOTYPENAME',
            field=models.CharField(db_column='EOTYPENAME', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='EOTerName',
            field=models.CharField(db_column='EOTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='HistLang',
            field=models.CharField(db_column='HistLang', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='REGNAME',
            field=models.CharField(db_column='REGNAME', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='REGTYPENAME',
            field=models.CharField(db_column='REGTYPENAME', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='SEXTYPENAME',
            field=models.CharField(db_column='SEXTYPENAME', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='TERNAME',
            field=models.CharField(db_column='TERNAME', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='TerTypeName',
            field=models.CharField(db_column='TerTypeName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='UkrAdaptScale',
            field=models.FloatField(db_column='UkrAdaptScale', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='UkrBall',
            field=models.FloatField(db_column='UkrBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='UkrBall100',
            field=models.FloatField(db_column='UkrBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='UkrBall12',
            field=models.FloatField(db_column='UkrBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='UkrPTAreaName',
            field=models.CharField(db_column='UkrPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='UkrPTName',
            field=models.CharField(db_column='UkrPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='UkrPTRegName',
            field=models.CharField(db_column='UkrPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='UkrPTTerName',
            field=models.CharField(db_column='UkrPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='UkrTest',
            field=models.CharField(db_column='UkrTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='UkrTestStatus',
            field=models.CharField(db_column='UkrTestStatus', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='bioBall',
            field=models.FloatField(db_column='bioBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='bioBall100',
            field=models.FloatField(db_column='bioBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='bioBall12',
            field=models.FloatField(db_column='bioBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='bioLang',
            field=models.CharField(db_column='bioLang', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='bioPTAreaName',
            field=models.CharField(db_column='bioPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='bioPTName',
            field=models.CharField(db_column='bioPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='bioPTRegName',
            field=models.CharField(db_column='bioPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='bioPTTerName',
            field=models.CharField(db_column='bioPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='bioTest',
            field=models.CharField(db_column='bioTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='bioTestStatus',
            field=models.CharField(db_column='bioTestStatus', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='chemBall',
            field=models.FloatField(db_column='chemBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='chemBall100',
            field=models.FloatField(db_column='chemBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='chemBall12',
            field=models.FloatField(db_column='chemBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='chemLang',
            field=models.CharField(db_column='chemLang', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='chemPTAreaName',
            field=models.CharField(db_column='chemPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='chemPTName',
            field=models.CharField(db_column='chemPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='chemPTRegName',
            field=models.CharField(db_column='chemPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='chemPTTerName',
            field=models.CharField(db_column='chemPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='chemTest',
            field=models.CharField(db_column='chemTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='chemTestStatus',
            field=models.CharField(db_column='chemTestStatus', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='deuBall',
            field=models.FloatField(db_column='deuBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='deuBall100',
            field=models.FloatField(db_column='deuBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='deuBall12',
            field=models.FloatField(db_column='deuBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='deuDPALevel',
            field=models.CharField(db_column='deuDPALevel', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='deuPTAreaName',
            field=models.CharField(db_column='deuPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='deuPTName',
            field=models.CharField(db_column='deuPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='deuPTRegName',
            field=models.CharField(db_column='deuPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='deuPTTerName',
            field=models.CharField(db_column='deuPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='deuTest',
            field=models.CharField(db_column='deuTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='deuTestStatus',
            field=models.CharField(db_column='deuTestStatus', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='engBall',
            field=models.FloatField(db_column='engBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='engBall100',
            field=models.FloatField(db_column='engBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='engBall12',
            field=models.FloatField(db_column='engBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='engDPALevel',
            field=models.CharField(db_column='engDPALevel', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='engPTAreaName',
            field=models.CharField(db_column='engPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='engPTName',
            field=models.CharField(db_column='engPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='engPTRegName',
            field=models.CharField(db_column='engPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='engPTTerName',
            field=models.CharField(db_column='engPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='engTest',
            field=models.CharField(db_column='engTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='engTestStatus',
            field=models.CharField(db_column='engTestStatus', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='fraBall',
            field=models.FloatField(db_column='fraBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='fraBall100',
            field=models.FloatField(db_column='fraBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='fraBall12',
            field=models.FloatField(db_column='fraBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='fraDPALevel',
            field=models.CharField(db_column='fraDPALevel', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='fraPTAreaName',
            field=models.CharField(db_column='fraPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='fraPTName',
            field=models.CharField(db_column='fraPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='fraPTRegName',
            field=models.CharField(db_column='fraPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='fraPTTerName',
            field=models.CharField(db_column='fraPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='fraTest',
            field=models.CharField(db_column='fraTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='fraTestStatus',
            field=models.CharField(db_column='fraTestStatus', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='geoBall',
            field=models.FloatField(db_column='geoBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='geoBall100',
            field=models.FloatField(db_column='geoBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='geoBall12',
            field=models.FloatField(db_column='geoBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='geoLang',
            field=models.CharField(db_column='geoLang', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='geoPTAreaName',
            field=models.CharField(db_column='geoPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='geoPTName',
            field=models.CharField(db_column='geoPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='geoPTRegName',
            field=models.CharField(db_column='geoPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='geoPTTerName',
            field=models.CharField(db_column='geoPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='geoTest',
            field=models.CharField(db_column='geoTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='geoTestStatus',
            field=models.CharField(db_column='geoTestStatus', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='histBall',
            field=models.FloatField(db_column='histBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='histBall100',
            field=models.FloatField(db_column='histBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='histBall12',
            field=models.FloatField(db_column='histBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='histPTAreaName',
            field=models.CharField(db_column='histPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='histPTName',
            field=models.CharField(db_column='histPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='histPTRegName',
            field=models.CharField(db_column='histPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='histPTTerName',
            field=models.CharField(db_column='histPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='histTest',
            field=models.CharField(db_column='histTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='histTestStatus',
            field=models.CharField(db_column='histTestStatus', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='mathBall',
            field=models.FloatField(db_column='mathBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='mathBall100',
            field=models.FloatField(db_column='mathBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='mathBall12',
            field=models.FloatField(db_column='mathBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='mathLang',
            field=models.CharField(db_column='mathLang', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='mathPTAreaName',
            field=models.CharField(db_column='mathPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='mathPTName',
            field=models.CharField(db_column='mathPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='mathPTRegName',
            field=models.CharField(db_column='mathPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='mathPTTerName',
            field=models.CharField(db_column='mathPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='mathTest',
            field=models.CharField(db_column='mathTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='mathTestStatus',
            field=models.CharField(db_column='mathTestStatus', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='physBall',
            field=models.FloatField(db_column='physBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='physBall100',
            field=models.FloatField(db_column='physBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='physBall12',
            field=models.FloatField(db_column='physBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='physLang',
            field=models.CharField(db_column='physLang', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='physPTAreaName',
            field=models.CharField(db_column='physPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='physPTName',
            field=models.CharField(db_column='physPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='physPTRegName',
            field=models.CharField(db_column='physPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='physPTTerName',
            field=models.CharField(db_column='physPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='physTest',
            field=models.CharField(db_column='physTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='physTestStatus',
            field=models.CharField(db_column='physTestStatus', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='spaBall',
            field=models.FloatField(db_column='spaBall', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='spaBall100',
            field=models.FloatField(db_column='spaBall100', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='spaBall12',
            field=models.FloatField(db_column='spaBall12', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='spaDPALevel',
            field=models.CharField(db_column='spaDPALevel', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='spaPTAreaName',
            field=models.CharField(db_column='spaPTAreaName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='spaPTName',
            field=models.CharField(db_column='spaPTName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='spaPTRegName',
            field=models.CharField(db_column='spaPTRegName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='spaPTTerName',
            field=models.CharField(db_column='spaPTTerName', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='spaTest',
            field=models.CharField(db_column='spaTest', null=True),
        ),
        migrations.AlterField(
            model_name='zno',
            name='spaTestStatus',
            field=models.CharField(db_column='spaTestStatus', null=True),
        ),
    ]
