# Generated by Django 4.2.7 on 2023-11-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_zno_areaname_alter_zno_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zno',
            name='OUTID',
            field=models.CharField(db_column='ID', editable=False, primary_key=True, serialize=False),
        ),
    ]
